# Mysql
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/atf2.0a?useSSL=true&useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8
    username: root
    password: bupt808

#启动端口addExpectationaddExpectation
server:
  port: 8000

# MyBatis
mybatis:
  typeAliasesPackage: com.atf.entity
  mapperLocations: classpath:/mappers/*.xml
  configLocation: classpath:/mybatis-config.xml
